import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    paddingTop: 50,
    paddingBottom: 65,
    paddingHorizontal: 50,
    backgroundColor: "#ffffff",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#cccccc",
    paddingBottom: 12,
  },
  headerTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  headerSubtitle: {
    fontSize: 9,
    textAlign: "center",
    color: "#666666",
  },
  preparerBlock: {
    marginBottom: 20,
    padding: 10,
    backgroundColor: "#f8f8f8",
    borderRadius: 4,
  },
  preparerTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
    textTransform: "uppercase",
    color: "#333333",
  },
  preparerRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  preparerLabel: {
    fontFamily: "Helvetica-Bold",
    width: 140,
    color: "#444444",
  },
  preparerValue: {
    flex: 1,
    color: "#000000",
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    backgroundColor: "#1e3a5f",
    color: "#ffffff",
    padding: 6,
    marginTop: 16,
    marginBottom: 8,
  },
  questionRow: {
    marginBottom: 10,
    paddingLeft: 4,
    borderLeftWidth: 2,
    borderLeftColor: "#e0e0e0",
  },
  questionText: {
    fontSize: 9.5,
    marginBottom: 3,
    lineHeight: 1.4,
  },
  questionNum: {
    fontFamily: "Helvetica-Bold",
  },
  answerLine: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 3,
  },
  answerLabel: {
    fontFamily: "Helvetica-Bold",
    marginRight: 6,
    color: "#333333",
  },
  answerYes: { color: "#166534" },
  answerNo: { color: "#991b1b", fontFamily: "Helvetica-Bold" },
  answerNA: { color: "#374151" },
  noteLine: {
    marginTop: 3,
    paddingLeft: 8,
    color: "#374151",
    fontStyle: "italic",
    lineHeight: 1.4,
  },
  bulletItem: {
    marginLeft: 12,
    marginTop: 1,
    color: "#555555",
  },
  pageNumber: {
    position: "absolute",
    fontSize: 8,
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: "center",
    color: "#999999",
  },
  footer: {
    position: "absolute",
    fontSize: 8,
    bottom: 32,
    left: 50,
    right: 50,
    flexDirection: "row",
    justifyContent: "space-between",
    color: "#999999",
    borderTopWidth: 0.5,
    borderTopColor: "#dddddd",
    paddingTop: 4,
  },
});
