import React from "react";
import { COLORS, FONT_STACK } from "./primitives";
import { format } from "date-fns";

interface FooterProps {
  submittedAt: Date;
}

export function Footer({ submittedAt }: FooterProps) {
  const dateStr = format(submittedAt, "MMMM d, yyyy");
  const timeStr = format(submittedAt, "h:mm a");

  return (
    <table width="100%" cellPadding={0} cellSpacing={0} role="presentation"
      style={{ width: "100%" }}>
      <tr>
        <td bgcolor={COLORS.green} style={{ backgroundColor: COLORS.green, padding: "16px 32px" }}>
          <p style={{ margin: 0, fontFamily: FONT_STACK, fontSize: 10, color: "rgba(255,255,255,0.6)",
            lineHeight: "1.6" }}>
            Generated by Aspen Valuations CBV Checklist Tool · {dateStr} · {timeStr} MT
            &nbsp;|&nbsp; Save this email to the client file · PS 130 minimum five-year retention
          </p>
        </td>
      </tr>
    </table>
  );
}
